### ISSUE TITLE
Sort Options

### ISSUE THREAD

**Issue by japierce1028** [ISDCF/registries#1]
Can we get a button that toggles between "sort by facility" and "Sort by code"

**Comment by palemieux** [comment]
Is sorting necessary if a search function is offered?

**Comment by japierce1028** [comment]
I think the display/printout NEED to be sorted at least by code for manual look up. I remember the comment by Steve that they need a print out since they may not go to the on-line version. I would assume they might also need a print out sorted by facility name. The current print out has both in two columns and it seems to meet industry need.

**Comment by palemieux** [comment]
The list is sorted by code. Ok?

**Comment by palemieux** [comment]
@SteveLLamb Is is sufficient if the PDF and online versions are sorted by `code`?

**Comment by SteveLLamb** [comment]
> @SteveLLamb Is is sufficient if the PDF and online versions are sorted by `code`?

Yes.

**Comment by SteveLLamb** [comment]
> Can we get the applicable lists with the ability to sort both by code and description please?
> I don’t believe we should reduce functionality from what was previously available.

Via Wade FYI.
