### ISSUE TITLE
Do we accept non-English descriptions?

### ISSUE THREAD

**Issue by ygonno** [ISDCF/registries#14]
I wonder if the registry will accept non-English descriptions for local domestic facilities and studios. So far in Japan, just a couple of international facilities have registered, but all the rest are using without registering. This is not only because of the language but there are more reasons. I'm just wondering if we can give them a little more chance to consider registering.

**Comment by palemieux** [comment]
Couple of questions:

* Is it ok for the `code` to remain a sequence of three characters in the set `[A-Z0-9]`?

* Should a printable `description` in ASCII (`[0x20-0x7E]`) be required, and any number of equivalent descriptions in other languages be optionally provided?

**Comment by radford-for-smpte** [comment]
It’s worth noting there are already `description` values outside of that range. E.g.

https://isdcf.github.io/registries/facilities.html#facility-AZU

**Comment by palemieux** [comment]
> It’s worth noting there are already description values outside of that range. E.g.

It looks like the exception rather than the rule. Assuming we adopt a more strict basic description, perhaps we need to preserve legacy descriptions with an _unknown_ language in case we cannot reach whoever registered it.

**Comment by ygonno** [comment]
> * Is it ok for the `code` to remain a sequence of three characters in the set `[A-Z0-9]`?
I think this should be the baseline of the rule.

> * Should a printable `description` in ASCII (`[0x20-0x7E]`) be required, and any number of equivalent descriptions in other languages be optionally provided?
That sounds reasonable to me. At least for the future registrations.

**Comment by japierce1028** [comment]
I like Yoshi's idea of an optional addition. Maybe in <> ? This one I would like to ask the bigger ISDCF group for feedback.

**Comment by SteveLLamb** [comment]
The larger question is that the code only expect for the CTT and what goes in the metadata facility  value? I would suggest the code is what is used within the CTT and Metadata (so it's only [A-Z0-9]) and machine readable on all systems. The registry is where you go to find the descriptions values if needed and that can indeed contain other characters, that can be local if needed. 

And I would argue against using description values in the metadata for exactly this reason.

**Comment by SteveLLamb** [comment]
I'm fairly certain we agreed English only for now? @japierce1028

**Comment by japierce1028** [comment]
The decision at ISDCF meeting was this would continue to be English only for now. Close it IMHO.
