### ISSUE TITLE
Can we provide localized registration forms?

### ISSUE THREAD

**Issue by ygonno** [ISDCF/registries#15]
I'm also hoping I can provide a registration form in Japanese as Google translated Form is okay but is not good enough.

**Comment by SteveLLamb** [comment]
Great idea, and I can have our localization teams translate for any other languages we need, as needed.

**Comment by ygonno** [comment]
Putting aside registration form, I'm updating my Japanese translation pages of DCNC converting them into WP templates.
Here is still an ugly integration of Facility page at: https://cinematechnology.jp/dcnc/dcnc-appendix-6-facility-codes
Happy to have any comments or suggestions.

**Comment by palemieux** [comment]
@SteveLLamb Can @ygonno be setup to create translations of the forms?

**Comment by SteveLLamb** [comment]
@ygonno studio code form is: https://forms.gle/GCwFGTbzPcn433xY6 and facility form is: https://forms.gle/vVUytft8J6qQQFvd6

If you do the translation and send directly to my email, we can work on this offline of here. 

I will create the translated forms that go to our tracking sheet, and embed links to those directly onto the page. Then we'll close this issue.

**Comment by ygonno** [comment]
Sounds good!
I will send @SteveLLamb candidate texts for those pages.

**Comment by SteveLLamb** [comment]
Closing this issue as per the discussion today. We may circle back to this later, but not going forward at this time.
