### ISSUE TITLE
New Language - Marathi

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#161]
New code as per IANA:
```
Type: language
Subtag: mr
Description: Marathi
Added: 2005-10-16
Suppress-Script: Deva
```

Needs to be added as per client's content being generated on request with this code.

**Comment by palemieux** [comment]
Audio and/or timed text?

**Comment by SteveLLamb** [comment]
> Audio and/or timed text?

This is coming in as spoken, but it's a dialect in India, and generally subbed into English, like Hindi.
