### ISSUE TITLE
New Language - Xhosa

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#202]
via email request:
--- 
    From: "Butler, Michael" <Michael.Butler@dolby.com>
    Date: June 22, 2021 at 12:43:32 PM MDT
    To: digitalcinemanaming@isdcf.com
    Subject: Xhosa Language Naming Convention
    Hello,
    
    We have a client who is releasing a film in Xhosa and would like to properly name the DCP. 
    
    As the ISDCF list does not contain Xhosa as a language, but the ISO 639-1 list does (as xh), could we suggest having "XH" listed as the Xhosa language code?
    
    Let us know if this isn't the correct place to request language codes be added.
    
    Thank you!
    
    Best,
    
    Michael
---

**Comment by palemieux** [comment]
@SteveLLamb Can you confirm it is both for spoken and written word?

**Comment by japierce1028** [comment]
Asked "Is Xhosa used as both a written language as well as a spoken language? " and the reply was both written/spoken.

**Comment by palemieux** [comment]
@japierce1028 Can you review https://github.com/ISDCF/registries/pull/205 ?
