### ISSUE TITLE
New Language - Afrikaans

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#232]
We got a new language for work coming in today for Afrikaans. We've had this request before, and I forgot to add it then. 

It's on IANA as:

```
%%
Type: language
Subtag: af
Description: Afrikaans
Added: 2005-10-16
Suppress-Script: Latn
%%
```
I'll add next week unless there is any objections.

**Comment by palemieux** [comment]
@SteveLLamb No objections from me, but the review should start once the PR is created :)
