### ISSUE TITLE
Add Scots Gaelic language

### ISSUE THREAD

**Issue by palemieux** [ISDCF/registries#253]
From Ian Ballantyne (Arteus Post Production):

> We are a Post Production Facility (Arteus Post Production – ISDCF code ‘APP’) based in Glasgow, Scotland. We produce small volumes of DCPs for mainly Scottish based producers, working in the English and Scots Gaelic languages. Scots Gaelic is actually growing in importance in media distribution generally, and we somewhat frequently package content for wider distribution to the  Gaelic speaking audience.
> There appears to be no mention of Scots Gaelic in the ISDCF documentation.
> There is an ISO 639-1 code for Gaelic, Scots Gaelic ‘gd’ – could this as ‘GD’ and ‘gd’ be used to identify the language elements within the naming convention?
> This would (obviously) be useful for describing content that is in the Gaelic language, with (for instance) English subtitles – ‘GD-EN-OCAP’

**Comment by SteveLLamb** [comment]
Code to be added as per IANA:

```
%%
Type: language
Subtag: gd
Description: Scottish Gaelic
Description: Gaelic
Added: 2005-10-16
%%
```
