### ISSUE TITLE
Discussion of expansion on fields required.

### ISSUE THREAD

**Issue by jamiegau** [ISDCF/registries#27]
I and others have suggested expanding on the fields against each facility.

I would suggest we have a discussion on this topic in general.  Should we add fields or just keep it simply? 
If we decide to add fields, what fields and the justification for them.

i.e.
url: pointing at company website
Transalation additions
Date changed

As some examples.
Is this a topic for the next meeting?

**Comment by japierce1028** [comment]
We can certainly discuss at the next ISDCF meeting. From now on we are going to be gathering that information, but we don’t have it for the first 1,000 facilities. See the “register your facility” link on the website. It points to a Google form capturing information.

**Comment by japierce1028** [comment]
From discussion at ISDCF meeting: Add URL and Contact Email. These fields are optional and going forward only. We should ask in the Google Form if the entry wants to publish either field (or none or both). This will apply to both Facility and Studio registry.

**Comment by SteveLLamb** [comment]
I will add an "opt out" field in the Google forms and tracking sheet. We are already collecting the info, and should include unless the user opts out.

**Comment by SteveLLamb** [comment]
Forms and Google sheets are completed. The fields to add to the registry for Facilities and Studios are:
- URL
- Contact
-- Name
-- Email
-- Address
-- OptOut

I think storing the info in the JSON is better longterm than the Google sheet (even if we don't present them to the page), hence the fields all present, including Opt Out, which can drive an If on the template to show or hide the info.

**Comment by jamiegau** [comment]
I do agree with Wade's comments in that we don't want to make a monkey for our backs in the need for updating any extra fields..
But I also think we do need some extra fields as "Googling the name" considering they are all similar and for similar companies is likely to be a difficult path.

I would suggest to indicate in the application/update FORM that a general company URL or Landing-page-URL specifically for driving people in the right direction if they require to contact them concerning a DCP,  Similarly for the Email.  ONLY an email (not name/address/etc) and the Email be described as a general Email (i.e. info@company.com) or specific "Email Alias" (ie. dcp_info@company.com) the entity can control to direct messages to the correct individual in the company.  The reason for this is the companies can modify the landing-page URL or general Email themselves after the fact and there will be unlikely any need for ISDCF to update these fields.

**Comment by SteveLLamb** [comment]
We won't be updating fields in currently existing records unless specifically requested by the entity. The reason for the additional fields is that we were capturing everything in a single field, making it difficult to parse. The amount of additions we get monthly is not that much of a burden to work on as adding 2-4 fields to a JSON vs 4-7, and there are only 3 of us making those updates/additions. 

As far as the fields themselves, I'm more apt to letting people use those fields as they wish. Some smaller entireties don't have generic contact info, and anything we can use to contact them if needed is better than nothing. There is also no expectation of auditing this list by us, it's on the owner of the entity to do such. If anyone has an update, they can submit a new request, not a big deal.

Once the record is in our registry it will remain for historical purposes indefinitely (in case the value is EVER used in a DCP).

**Comment by radford-for-smpte** [comment]
> * URL
> * Contact
>   -- Name
>   -- Email
>   -- Address
>   -- OptOut


I’m a bit concerned about OptOut, since presumably the contact data will still be visible in the JSON, both in the git repo as well as in the hosted Registries API server. I recommend we don’t offer that option. 

Additionally we should clarify in the form that the included contact info will be made publicly available and they should perhaps acknowledge that fact.

**Comment by SteveLLamb** [comment]
> > * URL
> > * Contact
> >   -- Name
> >   -- Email
> >   -- Address
> >   -- OptOut
> 
> I’m a bit concerned about OptOut, since presumably the contact data will still be visible in the JSON, both in the git repo as well as in the hosted Registries API server. I recommend we don’t offer that option.
> 
> Additionally we should clarify in the form that the included contact info will be made publicly available and they should perhaps acknowledge that fact.

Good point. I think then it's be better left on the Google form, and then that drives if the data goes into the JSON. I'm not adversed to removing it, but I know some people will not want this posted (and also to comply with GDPR we have to offer opting out).

**Comment by SteveLLamb** [comment]
To further this point, I have updated the form to include the following language on the opt out section of the Google forms:
"Unless you opt out, this contact information will be publicly available via the ISDCF DCNC website, the ISDCF Registry, and ISDCF GitHub repositories."

**Comment by japierce1028** [comment]
I think if someone "OptOut" for their data, it won't be put into the registry. It can/would remain on the very private google sheet, but that's the only place. We would have a record of those submitting that didn't OptOut.

**Comment by SteveLLamb** [comment]
@radford-for-smpte, @palemieux I'll take a first crack at updating the schema and fields for the JSON (adding values where we have them).

**Comment by japierce1028** [comment]
I want to add a new facility with URL and Contact email. Is this the right form:
  {
    "code": "APP",
    "description": "Artels Post Production"
    "URL": "arteus.co.uk"
    "contact": "ian.ballantyne@arteus.co.uk"
  },

**Comment by SteveLLamb** [comment]
> I want to add a new facility with URL and Contact email. Is this the right form:
> {
> "code": "APP",
> "description": "Artels Post Production"
> "URL": "arteus.co.uk"
> "contact": "[ian.ballantyne@arteus.co.uk](mailto:ian.ballantyne@arteus.co.uk)"
> },

No, but we are not done with that dev work. Just add the code and description. I’ll add the extra stuff on the dev branch.
