### ISSUE TITLE
Language JSON fields

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#29]
@radford-for-smpte, @palemieux A few things. 

1. The new JSON and schema is missing displayName. This should match the IANA description field for mapping other languages later, and conforming with IANA in general is a better idea. Where our DCNC traditionally has a different "name" that can go into the notes. 

2. We can remove the DCNC notes when talking about usage, as we have the "use" field to define that. As is used in the temp version on the ISDCF site. 

I suggest the following update based on the above items (using SQ and CMN as examples). Happy to do the legwork on this and updating the schema accordingly. 

Currently:
```
{
    "dcncTag": "SQ",
    "rfc5646Tag": "sq",
    "use": [
      "audio",
      "text"
    ],
    "comments": [
      "DCNC notes: Albanian"
    ]
  },
{
    "dcncTag": "CMN",
    "rfc5646Tag": "cmn",
    "use": [
      "audio"
    ],
    "comments": [
      "DCNC notes: (Audio only) - Chinese - Mandarin PRC"
    ]
  }
```
Updated:

```
{
    "dcncTag": "SQ",
    "displayName": "Albanian",
    "rfc5646Tag": "sq",
    "use": [
      "audio",
      "text"
    ]
{
    "dcncTag": "CMN",
    "displayName": "Mandarin Chinese",
    "rfc5646Tag": "cmn",
    "use": [
      "audio"
    ],
    "comments": [
      "DCNC notes: Chinese - Mandarin PRC"
    ]
  }


```

**Comment by palemieux** [comment]
The displayName is created at build time using CLDR, i.e. it is not necessary to include it in the register.

**Comment by SteveLLamb** [comment]
Roger that, thanks!
