### ISSUE TITLE
Get a new facility code button

### ISSUE THREAD

**Issue by japierce1028** [ISDCF/registries#3]
Can we add a simple button that goes to a page describing the steps needed to add a new code, the ability to add a code (that checks for a conflict) and a submission button?

**Comment by KirstenMills** [comment]
I would suggest we add this button for Studio code requests as well.

**Comment by palemieux** [comment]
I recommend keeping the instructions to obtain a new code on the main site, as it is today.

What about using a Google Form to simply collection and keep a record of the requests:

https://forms.gle/XmuEad93Duq3jFHK6

**Comment by SteveLLamb** [comment]
We should add an optional field to the form for deprecating old codes. For example:

> This code is replacing current existing code (optional)
> Example: AAA
> 
> Your answer

*With a caveat that it will be confirmed that they are authorized to speak on behalf of the old code's company.

**Comment by SteveLLamb** [comment]
This has been added as google form as suggested. One has been created for Studios as well. 
https://docs.google.com/forms/d/e/1FAIpQLSfbHLUyNDaZ6FPFICiqQjXWDLcOoiZbFWqYOYb83msh4fKS2Q/viewform?usp=sf_link

Will not add auto checking features yet, maybe on a future version. 

@japierce1028, shall we close this issue?
