### ISSUE TITLE
Code CAT not showing up in Facility Registry

### ISSUE THREAD

**Issue by japierce1028** [ISDCF/registries#322]
The entry CAT for Transylvania International Film festival shows up in the registry code, but doesn't show up in the on-line version. What's happening?

  {
    "code": "CAT",
    "contact": {
      "address": "Str. Meteor, Nr.2, Bloc T3, 27, Cluj-Napoca, Romania",
      "email": "vlad.translucid@gmail.com",
      "name": "Mr. Vlad Plaiasu"
    },
    "description": "Transilvania International Film Festival",
    "url": "https://tiff.ro"
  },

**Comment by palemieux** [comment]
The registry had stopped being updated since late November due to a GitHub idiosyncrasy. I have opened #323.
