### ISSUE TITLE
ISDCF registry site rebuild should be triggered by a change in the registry

### ISSUE THREAD

**Issue by palemieux** [ISDCF/registries#323]
It is currently triggered on a schedule.

**Comment by palemieux** [comment]
Closed by https://github.com/ISDCF/registries/commit/e207893ce1272c611dc1b0d683582c5c1e8c7fee

**Comment by ygonno** [comment]
I wonder if this is working or triggered since then.
I happen to know there is no update on my Japanese translation site, nor on the ISDCF site since 2022-02-16T19:06:36.

**Comment by palemieux** [comment]
I just merged https://github.com/ISDCF/registries/pull/343, so you should see an update soon.
