### ISSUE TITLE
PDF publishing - is it needed?

### ISSUE THREAD

**Issue by japierce1028** [ISDCF/registries#4]
There is a "download as a .pdf" button. I'm not sure if that is needed for the database. I am worried that the static download would be confusing. (I may be wrong on this idea.)

**Comment by jamiegau** [comment]
Yes, I don't see the need for this either.  And was wondering, how exactly does this page
https://isdcf.github.io/registries/facilities.html work in with the current page at
https://isdcf.com/dcnc/home/appendix-6-facility-codes.html
Does it replace it completely?  And you iframe it into the "https://isdcf.com/dcnc/home/appendix-6-facility-codes.html" page?  Or iframe the table (And any html tooling around it for sorting and searching) only?
I would also put a link in the README.md pointing to "https://isdcf.com/dcnc/home/appendix-6-facility-codes.html"  and however its done, have a single location indicating how to add to the list.
Currently via emailing "digitalcinemanaming@isdcf.com" but I remember at the meeting there was another suggesting about people summitting a git branch commit??

**Comment by jamiegau** [comment]
Oh, I would like to see mentioned in README.md that, for example, an external tool or application can pull master version of the file by simply..

wget https://raw.github.com/ISDCF/registries/master/src/main/data/facilities.json

As an example..  or type https://raw.github.com/ISDCF/registries/master/src/main/data/facilities.json into the browser to load it directly into a window as raw json data.

**Comment by radford-for-smpte** [comment]
> Oh, I would like to see mentioned in README.md that, for example, an external tool or application can pull master version of the file by simply..
> 
> wget https://raw.github.com/ISDCF/registries/master/src/main/data/facilities.json
> 
> As an example.. or type https://raw.github.com/ISDCF/registries/master/src/main/data/facilities.json into the browser to load it directly into a window as raw json data.

I agree that the README should make it clear that there is a stable, well-known URL that simply returns JSON suitable for integration into third-party tooling.

**Comment by palemieux** [comment]
> Does it replace it completely? And you iframe it into the "https://isdcf.com/dcnc/home/appendix-6-facility-codes.html" page?

Yes, this is the short-term plan. In the long-term, the entire DCNC subsite could be generated from the registers.

> wget https://raw.github.com/ISDCF/registries/master/src/main/data/facilities.json

The "right" way to make the registers available is through a RESTFul API exposed by a microservice. The API URIs would include the version of the JSON schema, e.g.

`wget https://register.isdcf.com/facilities/v1`

The microservice source code could be hosted in its own repo under `https://github.com/ISDCF`, e.g. `https://github.com/ISDCF/register-microservice`, and would be deployed as an AWS service.

This has a number of advantages:

* the ISDCF is not dependent on a third-party domain
* the ISDCF gets to decide exactly how to structure the API
* it decouples the data, i.e. this repo, from how it is served

This could be an excellent exercise for someone that wants to get involved in microservices and/or ISDCF.

**Comment by SteveLLamb** [comment]
I emailed this separately to a chain of people, but i'll repeat it here. PDF will still be required (which is ultimately not a big deal to provide, as already shown):

As an FYI, in most mastering facilities, printouts are readily handy so that operators/account teams don’t have to continually look at the site (mainly for being able to human parse what they are looking at). I suspect that will continue, even if machines are grabbing the info for orders or any automation tools.

**Comment by palemieux** [comment]
> PDF will still be required (which is ultimately not a big deal to provide, as already shown):

Can users be asked to "Print to PDF", or does a pre-generated PDF need to be made available?

**Comment by SteveLLamb** [comment]
> Can users be asked to "Print to PDF", or does a pre-generated PDF need to be made available?
If the formatting allows easy printing, then just a print would be fine. But my point is that we cannot discount the value of having a hard copy for reference for _some_ users. At the end of the day, as much we are trying to make this machine readable, we're also doing this to make the data correct, easier to maintain, and properly formatted. 

If the formatting doesn't allow for easy print, could we make a layout specifically for that?

**Comment by jamiegau** [comment]
To me is sounds like we need to spec this out a little more..

For example..

- create the base JSON github ISDCF/registries (Started)
- Spec out a document covering the basics of the API.
- Create a AWS microservice .. utilising what method? Language? docker container?  typically I would suggest we use a popular language (Python/javascript) easy to maintain down the track by others.
- As IFRAME is a tool of last resourt..  Implement a wordpress plugin that natively represents the registry in the ISDCF website. (php programming with wordpress knowledge required.)
- Any features for the ISDCF/wordpress site, such as PDF export.

Opinions on the above helpful.  I have not done a miroservice and only hacked together a wordpress plugin once. (It wasn't pretty, but did the job.  Php is not a language I use a lot)

I have other projects I want to stay focused on for now but could contribute in a few months.

**Comment by japierce1028** [comment]
Sounds like there is a need to have a "print to pdf" need. Can I request to close this issue with the answer: yes it is needed?
