### ISSUE TITLE
languages: remove audio usage from script-only entries

### ISSUE THREAD

**Issue by xslidian** [ISDCF/registries#424]
See #423

> Language tags with a script tag explictly specified should only be used for text purposes (picture / subtitles)

For example, "az-Cyrl" is "az" language written in Cyrillic alphabet (script). It should be used for subtitle.
For its corresponding audio track, "az" is enough.

Since the list is messed up with territory and script names, especially with my recent PR about Chinese, I have a suggestion for you to disscus in next meetings:
* modify description to include "text", e. g. "Tajik - Cyrillic _text_" for "tg-Cyrl"
* remove "audio/subtitles only" usage notes as they're already clear in "_use_"s

**Comment by SteveLLamb** [comment]
Replicating comment in PR here. 

Absence of the script subtag doesn't mean it's audio only. The script is not present if the script is the "default" (used normally in writing and speaking), which can be different per territory. Using `az` as the example, the default is `Arabic` so the `Arab` script subtag is not present. All non-script sub tags (and region where applicable) are on purpose and have been vetted for both audio and subs, by the territory subtags. In `Azerbaijan` you would just use `az`, but it you used (written or spoken) that same language in Russia, it would be `az-Cryl`, with optional `RU` as the end (in this case, we don't use the region subtags unless needed). And the dialect may or may not change based on the region. 

Another way to put this, we don't put `Latn` on `en`, as it's assumed using Latin characters, and just `en` is both audio and text. 

> remove "audio/subtitles only" usage notes as they're already clear in "use"s

This was a holdover from the original DCNC, it's there for legacy.

**Comment by xslidian** [comment]
> > remove "audio/subtitles only" usage notes as they're already clear in "use"s
> 
> This was a holdover from the original DCNC, it's there for legacy.

It's not easy to maintain manually. I prefer it to be generated from the `"use"` array.
We've reviewed #380 many times, but we still missed "audio only" usage note for `QTM`. 😄
