### ISSUE TITLE
languages: complement region-specific entries for ff-NG/SN, ha-NG, ks-IN, mni-IN, mn-CN, sr-BA/ME, sd-IN & tg-TJ

### ISSUE THREAD

**Issue by xslidian** [ISDCF/registries#426]
See PR #425

> As a result of my recent changes on usage purposes ([tags with script tag became text-only](https://github.com/ISDCF/registries/pull/423)), people will be unable to mark a track as targeting one specific territory under affected languages. 
> This PR allows existing customers a corresponding choice.
> 
> DCNC codes are made up following existing 4-letter style (`LLTT`, language code + territory code).

**Comment by SteveLLamb** [comment]
Again, there are some defaults built into both CLDR and IANA tags, where the language and/or script is the "default" used, there is no need to include. The region and script subtags are meant to further refine the dialects spoken and written in specific regions within a certain country. There is no need to add sub-region tags when you have the default region for the language.

**Comment by xslidian** [comment]
Oh sorry, I was focusing on tags alone and forgot the `-XX` syntax in DCNC. I'll check if the PR is still needed with CLDR likelySubtags data at a later time.

**Comment by palemieux** [comment]
Look for the `Suppress-Script` field in the IANA language subtag registry: it indicates the "default" script.
