### ISSUE TITLE
Bug with Validator?

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#44]
While trying to validate locally for my last issue/PR before pushing, it choked on the .DS_Store file. Needs to be ignored. 

[Error: ENOENT: no such file or directory, open 'src/main/schemas/.DS_Store.schema.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'src/main/schemas/.DS_Store.schema.json'
}

**Comment by radford-for-smpte** [comment]
I don't think this is an issue specifically in `ISDCF/registries`:
```
$ git clone https://github.com/ISDCF/registries
$ cd registries
$ npm i
$ touch src/main/schemas/foo
$ npm run validate
Checking facilities
Checking languages
Checking studios
$ npm test
<no errors>
```

**Comment by SteveLLamb** [comment]
Roger that, I was running the validate incorrect. Thanks!
