### ISSUE TITLE
Distributed by?

### ISSUE THREAD

**Issue by japierce1028** [ISDCF/registries#468]
Is there a need to add a field for "Distributed by" so a recipient of a DCP can know where to go to find information about the content. Most start by going to the Deluxe Portal, but for the non-Deluxe distributed content where should they go? 

It's a thought, not a requirement. Maybe to discuss at the next ISDCF meeting?

**Comment by SteveLLamb** [comment]
Why not go to Studio (content owner), then Facility?

**Comment by japierce1028** [comment]
At ISDCF meeting we decided this was not possible / needed.
