### ISSUE TITLE
Add DCI's HDR Addendum to registries

### ISSUE THREAD

**Issue by radford-for-smpte** [ISDCF/registries#475]
Add CPL metadata from Section 5.1 of:

 https://www.dcimovies.com/specification/DCI-HDR-Addendum-v100_2022-0330.pdf

Also include a new Content Type designator to the Naming Convention

**Comment by japierce1028** [comment]
I think adding HDR1 is a good idea as a content type modifier in the naming convention.

**Comment by SteveLLamb** [comment]
Close via https://github.com/ISDCF/registries/pull/488
