### ISSUE TITLE
npm test fails when ISDCF_SKIP_URL_CHECK=1

### ISSUE THREAD

**Issue by msheby** [ISDCF/registries#510]
A fresh git clone can't pass `npm test`; I've even set `ISDCF_SKIP_URL_CHECK` in my environment.

**Comment by SteveLLamb** [comment]
Try: `export ISDCF_SKIP_URL_CHECK=true` instead. You'll be able to run `npm run validate` and `npm run canonicalize` only. You'll need to actually get a key for checking the safe browsing to run `npm run test`. 

@palemieux perhaps we should clarify this better in the readme?

**Comment by SteveLLamb** [comment]
> Setting the variable to `true` instead of `1` has no effect; `npm run validate` fails with `Bad API call` although `npm run canonicalize` runs cleanly.

The rest of validation works fine? That is just the URL checking returning out. The validation for each JSON is prior and has its own separate error message if failure occurs. There is no message if it passes should look like this:

```
LLambsMB:registries llambs$ npm run validate

> isdcf-registries@1.0.1-beta.1 validate
> node src/main/scripts/validate.js

Checking audioconfigs
Checking contentmodifiers
Checking contenttypes
Checking cplmetadataexts
Checking facilities
Checking kdmforensicflags
Checking languages
Checking projectoraspectratios
Checking ratings
Checking studios
Checking territories
Checking uls
Bad API call
```
