### ISSUE TITLE
Add contact email and URL to Facility json database

### ISSUE THREAD

**Issue by japierce1028** [ISDCF/registries#53]
At the ISDCF meeting we decided that there be two optional fields to list the facilities contact email and facility URL. These will not be confirmed or updated over time. When registering via a Google form we will give an "opt out" option and also allow a facility to "update" their contact information.

**Comment by japierce1028** [comment]
There was also discussion to add "date entered" to the entry. I would like to confirm/discuss if this would be valuable in this thread.

**Comment by SteveLLamb** [comment]
There is no user benefit to this, as we will never remove records. From a programming side, we can see with commits when a record was added/edited. 

Duplicate information as discussed in #27, closing.
