### ISSUE TITLE
Arabic - Saudi Arabia language code is not right

### ISSUE THREAD

**Issue by cfadamp** [ISDCF/registries#531]
in file https://github.com/ISDCF/registries/blob/master/src/main/data/languages.json (and also in the registry page: https://registry-page.isdcf.com/languages/ ) the RF5646 language code for "Arabic - Saudi Arabia" spoken audio language is "aec".

As far as I knew it should be "ar-SA" for "Arabic - Saudi Arabia", and "aec" is meant to be the code for "Saidi Arabic".  It looks like "Saidi Arabic" and "Arabic - Saudi Arabia" have been mixed up.

So if I am correct, the right entry should be something like the following (I am not sure about the dcncTags) :

`{
    "dcncLanguage": "Arabic - Saudi Arabia",
    "dcncTag": "ARSA",
    "rfc5646Tag": "ar-SA",
    "use": [
      "audio",
      "text"
    ]
  },
{
    "dcncLanguage": "Saidi Arabic",
    "dcncTag": "AEC",
    "rfc5646Tag": "aec",
    "use": [
      "audio",
      "text"
    ]
  },`

instead of

`{
    "dcncLanguage": "Arabic - Saudi Arabia",
    "dcncTag": "AEC",
    "rfc5646Tag": "aec",
    "use": [
      "audio",
      "text"
    ]
  },`

**Comment by SteveLLamb** [comment]
Looks like this was an oversight in spelling. `Ṣaʽīdi Arabic` is the correct Display name for `aec`. 

`Arabic - Saudi Arabia` will be updated and `ARSA` would be the proper `dcncTag` following the convention we are presently using. 

Thanks for the catch!

**Comment by SteveLLamb** [comment]
@cfadamp This has been updated. Please check out the PR, and we'll merge after meeting next week.

**Comment by cfadamp** [comment]
@SteveLLamb It looks fine now, thanks!
