### ISSUE TITLE
Language code in DCP name for multiple main languages

### ISSUE THREAD

**Issue by samuel-krupke** [ISDCF/registries#547]
Hello,

I am currently involved in the mastering process of a documentary film about citizens in the European Union and I was wondering about the right language code to use in the DCP title. Our film has only one audio version which features multiple languages. The film is composed of many interviews of which the majority is held in english, german and italian. That makes determining a main audio language quite difficult. There are three further languages spoken (french, russian, lithuanian), but only briefly or in the background, so I assumed those could be ignored. The director originally wanted to include many more languages but that was too complicated to produce. The film is not trying to depict protagonists exploring 'foreign' land, different people are shown in their homes, respectively.
I could not find a language code on the ISDCF website for multiple main languages in one film - I only found codes for international distribution territories, no spoken language and multiple subtitle languages.
I found the code 'mul' for multiple on the iana website, however (https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)

What is your advice on this topic?

Kind regards
Samuel

**Comment by palemieux** [comment]
_mul_ should not be used in CPL metadata, which conforms to RFC 5646. Two options come to mind for CPL metadata:
* pick one of the languages as the primary language and use it consistently
* have an empty language tag

For the naming convention, _MUL_ could be used but would then not match the CPL metadata, which is not great.

@samuel-krupke Any strong feeling about picking one primary language (arbitrarily maybe but consistently)?

@radford-for-smpte and @SteveLLamb Any advice?

**Comment by SteveLLamb** [comment]
> Our film has only one audio version which features multiple languages. The film is composed of many interviews of which the majority is held in english, german and italian. That makes determining a main audio language quite difficult. There are three further languages spoken (french, russian, lithuanian), but only briefly or in the background

> pick one of the languages as the primary language and use it consistently

To Pierre's point, if you have a single audio track, are you matching subtitles to whatever you consider the "main" audio track? If so, I'd pick whatever you consider the "base" and use that as your language in the name.

**Comment by samuel-krupke** [comment]
Would an empty language Tag mean putting 'NULL' in the name? Afaik 'XX' means no language at all, right?

Two subtitle tracks were made to the same audio track, english and german. The director is native german, the complete crew quite international, which is the reason why the subtitle tracks exist in those two languages. Maybe I should measure the screen time of the languages. I wouldn't want to use MUL if it's incompatible with metadata.

**Comment by SteveLLamb** [comment]
> Would an empty language Tag mean putting 'NULL' in the name? Afaik 'XX' means no language at all, right?
> 
> Two subtitle tracks were made to the same audio track, english and german. The director is native german, the complete crew quite international, which is the reason why the subtitle tracks exist in those two languages. Maybe I should measure the screen time of the languages. I wouldn't want to use MUL if it's incompatible with metadata.

Yes `XX` means "no language". You COULD use `NULL` in the CTT, but all metadata would have language element not present (for "undefined"), like with using `XX` (where able to, some are required). 

Rather than thinking of the director or crew, it should be more what's the intended singular language of the audience (from an audio perspective), or is it expected that the viewer needs to be both speaking English/German?

**Comment by samuel-krupke** [comment]
The german subtitle version subtitles everything except german, so nobody needs to be bilingual. The english subtitle version is for generic international audiences, meaning everything that is not standard english is subtitled. Parts in heavy Dublin accent are subtitled in the EN version, too.

**Comment by SteveLLamb** [comment]
> The german subtitle version subtitles everything except german, so nobody needs to be bilingual. The english subtitle version is for generic international audiences, meaning everything that is not standard english is subtitled. Parts in heavy Dublin accent are subtitled in the EN version, too.

Then there is your answer. You have 2 versions, a `DE` "local" version and a `EN` "international" version. Label the Audio and Subs accordingly for each version they are, and if there are other languages in the documentary, that is fine, but no need to label them.

**Comment by samuel-krupke** [comment]
Thank you for your answers and help! We'll use the last suggestion from Steve :)
