### ISSUE TITLE
Confirm that studios and facilities with the same code have consistent contact information

### ISSUE THREAD

**Issue by palemieux** [ISDCF/registries#597]
Should studios and facilities that have the same code have consistent contact information?

Are there studios and facilities with the same code but completely different organization?

See https://github.com/ISDCF/registries/pull/594 as an example.

**Comment by japierce1028** [comment]
This sounds like the right thing to do: No code can be in both studio/facility with the same code unless they are the same organization. I think we should ask the SLACK group for comments.

**Comment by SteveLLamb** [comment]
> No code can be in both studio/facility with the same code unless they are the same organization

Depends what you mean by organization. There may be a studio that does their own mastering, but with a different umbrella org structure and contact info but wish to use the same code for consistency. I don't think we should restrict that.

**Comment by japierce1028** [comment]
Sounds like this is not an issue. I will still keep track of new entries and steer them to have the same codes when both are entered at the same time.
