### ISSUE TITLE
How to share full data with admins for Opt-OUT entries

### ISSUE THREAD

**Issue by ygonno** [ISDCF/registries#670]
I wonder how I should share full information with administrators about Opt-OUT entries that were not received via the official form.
I suppose any data written here will be visible to anybody.

**Comment by palemieux** [comment]
I would email @japierce1028 or digitalcinemanaming@isdcf.com with the information

**Comment by ygonno** [comment]
Done as suggested.
Please close this if it looks good.

**Comment by japierce1028** [comment]
Actually I would like you to enter the information on the google form so it get's captured (I did it for this entry so you don't need to do it again). Just include in the notes that you are going to directly enter into GitHub.

**Comment by ygonno** [comment]
Understood. I will do so from the next time.
