### ISSUE TITLE
Need for "Unknown" languages code(s)

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#783]
We recently saw a release with a made up language as base spoken language and subs over the entire feature, in this case english subs. `EN-XX`, `XX-EN`, and `EN-EN` all don't apply in this case. We had confirmation from the production company this is a made up language, like GoT languages. 

Doing some further research we need:
- Code for “Unknown” or “Made up” Language – think GoT or SW weird whatever alien language
- Code for Language we know is real but likely marked as a “dead” language that will never get a registered code via IANA.

**Comment by palemieux** [comment]
Potential options:

* `und`: Undetermined language
* `x-`: private use subtag

**Comment by palemieux** [comment]
RFC 5646 recommends against using `mis`.

**Comment by palemieux** [comment]
@SteveLLamb `und` is ok?

**Comment by SteveLLamb** [comment]
> @SteveLLamb `und` is ok?

Yes, this works for me. I'll put this in after the meeting this week.

**Comment by SteveLLamb** [comment]
> I know this is late-breaking, but someone mentioned `art`: `Artificial languages`!

@msheby moving this one to it's own issue, as need schema update to address.
