### ISSUE TITLE
Facility location request

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#8]
Idea. 

Seeing as we are trying to do this properly from the get-go, could we add a field for location, for facilities that have multiple locations. Not a location for the facilities per se like an address, but general nested location, for sorting purposes. 

Using Deluxe as an example, Deluxe as main facility and then an iterative list of locations that are all branched off the main, such as Burbank, London, etc....

**Comment by palemieux** [comment]
See proposed form at https://github.com/ISDCF/registries/issues/3#issuecomment-646727764

**Comment by SteveLLamb** [comment]
I was thinking nested format with locations under Company for the schema structure and listed in registry. That might be a little too complex, but we might have other registries that have nested list values within a main header (and might require a "parent" company code, and then "child(ren)" for locations. Think of the property lists in extension metadata, or ContentVersionLists as an example. Maybe we only worry about that for metadata items that allow lists.

That works for the form, with a 1-1 to the codes.

**Comment by SteveLLamb** [comment]
No further need to discuss and what we have works for now.
