### ISSUE TITLE
Languages - MISSING VALUE - XX

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#85]
Proposal is to use this as the RFC tag reference for "no lanugage" (XX) in the DCNC:

Type: language
Subtag: zxx
Description: No linguistic content
Description: Not applicable
Added: 2006-03-08
Scope: special
%%

This missing value is preventing deletion of the bottom table at:
https://www.isdcf.com/site/dcnc-appendix-1ab-language-codes/

**Comment by palemieux** [comment]
See initial discussion at #47

**Comment by palemieux** [comment]
@SteveLLamb Is the proposal to add an entry that has ZXX as DCNC code and an empty RFC 5646 tag?

**Comment by SteveLLamb** [comment]
> @SteveLLamb Is the proposal to add an entry that has ZXX as DCNC code and an empty RFC 5646 tag?

No, use RFC code as "zxx", so that we can use that value in CLDR, and the Display will read "No linguistic content", and the DCNC code as "XX" as it already used. 

Users can then either use "zxx" in their `<Language>` metadata elements or just not include a `<Language>` element to denote there is no language present.

**Comment by palemieux** [comment]
I am concerned that implementers have consistently been told not to include a language code if no spoken language is associated with the asset. Is `zxx` being added only to satisfy the needs of CTT?

**Comment by SteveLLamb** [comment]
> I am concerned that implementers have consistently been told not to include a language code if no spoken language is associated with the asset. Is `zxx` being added only to satisfy the needs of CTT?

Yes, to be able to put in XX for the CTT. I was going to put this note, but wanted to get feedback first (which obv aligns with my original thought ).

"comments": [
"This code is only for use in the CTT. If using 429-16 and/or 429-7 metadata, the absence of the `<Language>` element(s), where applicable, shall denote 'No linguistic content'."
]

**Comment by SteveLLamb** [comment]
Create as hard coded exception to be rendered in table and NOT in JSON. 
- Add similar to Null for Studios and Facilities.

**Comment by SteveLLamb** [comment]
Issue created for hard coding on page builds via https://github.com/ISDCF/registries-site/issues/18, closing issue.
