### ISSUE TITLE
Languages - MISSING VALUE - MOS

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#86]
There is no value within IANA for MOS used within the DCNC.

This missing value is preventing deletion of the bottom table at:
https://www.isdcf.com/site/dcnc-appendix-1ab-language-codes/

**Comment by SteveLLamb** [comment]
See initial discussion at #47

**Comment by palemieux** [comment]
`MOS` is completely unrelated to language and should be a practice specified outside of the language table -- presumably RDD 52.

**Comment by SteveLLamb** [comment]
I 100% agree, it should be in the sound config area, and usually we use this in the CTT as such, with XX in the language fields. This was in the original table in the language (for reason unknown and not agreed to me), which is why this issue is present here. 

We need to get consensus to remove from the language area and move to sound field, and then we can close this issue.

**Comment by SteveLLamb** [comment]
Not to be added to language table. Will be kept in the audio config table and the illustrated guide to be updated by @japierce1028.
