### ISSUE TITLE
Languages - Sortable field TBD

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#87]
As discussed at ISDCF meeting 9/23. There is a need to determine which field(s) the table should be sorted by. 

This missing value is preventing deletion of the bottom table at:
https://www.isdcf.com/site/dcnc-appendix-1ab-language-codes/

**Comment by palemieux** [comment]
See initial discussion at #47

**Comment by SteveLLamb** [comment]
My proposal is to use the current info the in the comments sections such as:
DCNC notes: Catalan

To a new column labeled "DCNC " and make these fields match the "old" conformed table and use this as the column to sort on. Then the comments can truly be comments. 

The column layout would be:

Language | RFC 5646 Tag | DCNC Code | DCNC Name | Intended use | Comments

I'm also looking into a user sortable feature, but that is later.

**Comment by radford-for-smpte** [comment]
I would suggest that if a new column is added for sorting, that's not much different than just maintaining the sort explicit in [`languages.json`](https://github.com/ISDCF/registries/blob/master/src/main/data/languages.json).

If we did opt for a new JSON property, I'd recommend that it be omitted from the table. The "Language" field should be all that's seen.

**Comment by SteveLLamb** [comment]
I'm talking about presenting the data that is already there in the "Comments" as "DCNC Notes" in a way that is the key for sorting, rather than just being in the comments field.  Using the example of Chinese from the meeting. 

Current:

Language | RFC 5646 Tag | DCNC Code | Intended use | Comments
Chinese | cmn | CMN | audio | DCNC notes: (Audio only) - Chinese - Mandarin PRC
Simplified Chinese | cmn-Hans | QMS | text | DCNC notes: (Subtitles only) - Chinese - Mandarin Simplified

Proposed:

Language | RFC 5646 Tag | DCNC Code | DCNC Name | Intended use | Comments
Chinese | cmn | CMN | audio | Chinese - Mandarin PRC | Audio only
Simplified Chinese | cmn-Hans | QMS | text | Chinese - Mandarin Simplified | Subtitles only

**Comment by SteveLLamb** [comment]
Notes
- Update current language column to CLDR language.
- Move comment languages to DCNC language column (default sort). 
- Make all columns sortable.
- Widen page, remove top scroll, full page length. 

New issues to be added, and this comment will be closed.

**Comment by SteveLLamb** [comment]
All new issues have been created for this item as discussed in meeting 9/24, closing this issue.
