### ISSUE TITLE
Abandoned Entry

### ISSUE THREAD

**Issue by ygonno** [ISDCF/registries#879]
I noticed one facility terminated its business last year but the entry is not updated.

I wonder how we want to handle such an abandoned entry.

1. Leave it unchanged until the original registrant reports its updated status.
2. Update the data once someone discovers an error on a best-effort basis.
3. Query (ping) all contacts periodically for any updates. (**NO**)

Any thoughts?

**Comment by palemieux** [comment]
I suggest we leave it as-is until someone reports an issue, e.g., "tried to contact the facility and learned that it was out-of-business"

**Comment by ygonno** [comment]
Probably that would be practical as this list is maintained by volunteer.  I don't think this will cause any issue.  I hope there will be someone to report.

I'm a little concerned that the case was about one of long-established facilities in Japan and everyone knows about its closure.  Leaving it may give an impression this list is not well-maintained.

**Comment by jamiegau** [comment]
Personally, I think we need to have some type of third-party test to see if an entry is no longer valid.
Like a registered Email address that sends out a check request every year.

Just like ICANN does for domain registrations and upkeep of support emails etc.

**Comment by SteveLLamb** [comment]
We had already discussed this in both ISDCF meetings and offline while creating the registry. The list is completely voluntary, and while we have a value for `deprecated`, that was really meant for when a new code is meant to replace a current one, not signal a studio or facility is no longer in business. We already never remove codes, for historical purposes when looking up old CPLs. I'm not sure what we would gain from having a `no longer in business` or similar flag in our registry.

**Comment by jamiegau** [comment]
For historical reasons makes sense.  It's a "do-nothing" result.  Mark it deprecated if requested.
Otherwise, document this position.

**Comment by ygonno** [comment]
It seems missing the point.  No one suggests deleting an entry, creating a new flag or changing the schema.  Don't do that, please.

The question was how we can better update forgotten changes.
If we are happy leaving unupdated entries, just leave them.  It won’t harm anybody.
I will put a note for Japanese users to avoid false expectations.
