### ISSUE TITLE
Meänkieli language code?

### ISSUE THREAD

**Issue by japierce1028** [ISDCF/registries#885]
My name is Tony and I’m a producer at Iris Film in Luleå, a production company close to the arctic circle in northernmost Sweden. 

We at Iris Film are producing the very first feature film where the spoken language is Meänkieli, a official minority language in Sweden, a language spoken in the Tonevalley region in Sweden. 
We are in post production at the moment, finished film expected in late august. 
In discussion with the post production facility we stumbled upon the problem of the language code for naming the DCP, since there is no code for Meänkieli at this moment. 

Is there a possibility of introducing a language code for Meänkieli? 

Here is some information regarding the language of Meänkieli:
https://sweden.se/life/equality/national-minorities-in-sweden
https://en.wikipedia.org/wiki/Official_minority_languages_of_Sweden
https://sweden.se/life/swedish-language/swedish-and-other-languages-in-sweden
https://en.wikipedia.org/wiki/Me%C3%A4nkieli

Thank you for your time!

Sincerely,
Tony Österholm

**Comment by palemieux** [comment]
The IANA/RFC 5646 language code is:

ˋ`ˋ
Type: language
Subtag: fit
Description: Tornedalen Finnish
Description: Meänkieli
Added: 2009-07-29
ˋ`ˋ

**Comment by SteveLLamb** [comment]
FWIW, we been using the issue tracker as new language requests come in. I'll add this in as noted by Pierre within the next week.
