### ISSUE TITLE
Update Language Canonical sort

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#89]
Canonical sort is currently not defined. 

Suggested by RFC Tag. 

Thoughts?

**Comment by SteveLLamb** [comment]
Currently while working on current issues the sort value will be by Language (DCNC language).

**Comment by jamiegau** [comment]
If we are discussing the Wade misgivings on the implementation.  I have some comments.
We should depreciate the older table and remove it IMO.
People are loath to learn new things.  And I feel the new table is suitable if used in a different way.  For example, there are many different chinese languages.  What to use? Want to see them all at once.. If you did a search on the table to only return items with Chinese in the description, all the variants would then be displayed, giving the user a similar result.

And realistically its not a huge list... on a printout its only 2 pages (see PDF).  Not difficult for people to visually scan on paper.

I personally consider the new version adequate, but I would suggest to make it more suitable to wads comments.
Reformat column Comments from/to: "DCNC notes: (Audio only) - Chinese - Mandarin PRC" to "DCNC notes: - Chinese - Mandarin PRC (Audio only)"
And allow column based sorting.  It would be more visually pleasing and sort more effectively if you make that feature available.

You could also enable the PDF format to be based on the sorted/search output in the table, but I imagine that's a big ask, so forget it.

**Comment by SteveLLamb** [comment]
@jamiegau 

All usability concerns raised are being handled within other issue tickets created today, both within the registries and registries-site reps, as already discussed with Wade and agreed to by the group. We will revisit the concerns after the issues are finished. 

This particular issue is only for XML Canonicalization, discussion of which field to use, and adding in the functionality for validation the canonicalization. This is unrelated to other issues, and was created as a breadcrumb for later good practice on the backend side of things.

**Comment by palemieux** [comment]
@jamiegau For your reference:

> Reformat column Comments from/to: "DCNC notes: (Audio only) - Chinese - Mandarin PRC" to "DCNC notes: - Chinese - Mandarin PRC (Audio only)"

See https://github.com/ISDCF/registries/issues/88

> And allow column based sorting. It would be more visually pleasing and sort more effectively if you make that feature available.

See https://github.com/ISDCF/registries-site/issues/15
