### ISSUE TITLE
Add Studio - SPC

### ISSUE THREAD

**Issue by SteveLLamb** [ISDCF/registries#895]
Sony Pictures Classics (SPC)

Adding on behalf of Allison Mackie allison_mackie@spe.sony.com

**Comment by jackers2024** [comment]
Aren't the films from Sony Pictures Classics distributed by Sony Pictures Releasing?

**Comment by SteveLLamb** [comment]
They specifically asked for this code and naming for their classics, as such, there is already content created for them with this code on their request. Their non-classics code is:
```
SPE | SONY PICTURES ENTERTAINMENT
```
